spring.application.name=Library-Management-Project
server.port=${PORT:4321}

# ✅ Neon PostgreSQL connection
spring.datasource.url=jdbc:postgresql://ep-fragrant-credit-aod4tkdt.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Fkeliy94pgJX
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=*

# Mail config
MAIL_USER=librarymanagementsystem2026@gmail.com
MAIL_PASS=xnhsqqtnecbsebwu

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com